[package]
name = "git-wt"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.28"
nucleo-matcher = "0.3"
inquire = "0.9"
color-eyre = "0.6.5"